### ISSUE TITLE
CachingRetrofit should be using PermsUtil instead of handling permissions internally

### ISSUE THREAD

**Issue by MichaelSteer** [CMPUT301W18T02/Taskr#56]

**Comment by xrendan** [comment]
Where is it dealing with permissions locally

**Comment by MichaelSteer** [comment]
https://github.com/CMPUT301W18T02/Taskr/blob/master/app/src/main/java/ca/ualberta/taskr/models/elasticsearch/CachingRetrofit.kt 

Line 115. Use nathans class to do it
